# Description
#   Randomly Insults or compliments someone for you
#
# Commands:
#   hubot insult <@user | Internet Explorer | Justin Bieber> - hey @user, <random insult here>
#   hubot compliment <@user | Boss | Your wife> - hey Wife, <random comliment here>
#
# Notes:
#   This can be harmful in an office, if your random insult hit somebody hard, be sure to @hubot compliment them
#
# Author:
#   altryne

insults = ["Your birth certificate is an apology letter from the condom factory."
, "Is your ass jealous of the amount of shit that just came out of your mouth?"
, "You must have been born on a highway because that's where most accidents happen."
, "Yo're so ugly, when your mom dropped you off at school she got a fine for littering."
, "I don't exactly hate you, but if you were on fire and I had water, I'd drink it."
, "I'd like to see things from your point of view but I can't seem to get my head that far up my ass."
, "If I wanted to kill myself I'd climb your ego and jump to your IQ."
, "Your family tree must be a cactus because everybody on it is a prick."
, "I could eat a bowl of alphabet soup and shit out a smarter statement than that."
, "Roses are red violets are blue, God made me pretty, what happened to you?"
, "It's better to let someone think you are an Idiot than to open your mouth and prove it."
, "If you are going to be two faced, at least make one of them pretty."
, "The only way you'll ever get laid is if you crawl up a chicken's ass and wait."
, "Shut up, you'll never be the man your mother is."
, "If you're gonna be a smartass, first you have to be smart. Otherwise you're just an ass."
, "Well I could agree with you, but then we'd both be wrong."
, "Somewhere out there is a tree, tirelessly producing oxygen so you can breathe. I think you owe it an apology."
, "You're not funny, but your life, now that's a joke."
, "Hey, you have somthing on your chin... no, the 3rd one down"
, "You are proof that God has a sense of humor."
, "It looks like your face caught on fire and someone tried to put it out with a hammer."
, "Why don't you slip into something more comfortable -- like a coma."
, "You're so fat the only letters of the alphabet you know are KFC."
, "If I were to slap you, it would be considered animal abuse!"
, "Your face makes onions cry."
, "Learn from your parents' mistakes - use birth control!"
, "Maybe if you ate some of that makeup you could be pretty on the inside."
, "If you spoke your mind, you'd be speechless."
, "At least when I do a handstand my stomach doesn't hit me in the face."
, "You're so fat you need cheat codes to play Wii Fit"
, "Oh my God, look at you. Was anyone else hurt in the accident?"
, "Don't feel sad, don't feel blue, Frankenstein was ugly too."
, "You didn't fall out of the stupid tree. You were dragged through dumbass forest."
, "Do you still love nature, despite what it did to you?"
, "You are proof that evolution CAN go in reverse."
, "Why don't you check eBay and see if they have a life for sale."
, "It's kinda sad watching you attempt to fit your entire vocabulary into a sentence."
, "You do realize makeup isn't going to fix your stupidity?"
, "I'll never forget the first time we met, although I'll keep trying."
, "You're so ugly, when you got robbed, the robbers made you wear their masks."
, "Shock me, say something intelligent."
, "What are you doing here? Did someone leave your cage open?"
, "Looks like you traded in your neck for an extra chin!"
, "You shouldn't play hide and seek, no one would look for you."
, "You are so stupid, you'd trip over a cordless phone."
, "If you really want to know about mistakes, you should ask your parents."
, "Why dont you shut up and give that hole in your face a chance to heal."
, "If I wanted to hear from an asshole, I'd fart."
, "Looks like you fell off the ugly tree and hit every branch on the way down."
, "I love what you've done with your hair. How do you get it to come out of the nostrils like that?"
, "You fear success, but really have nothing to worry about."
, "I don't know what makes you so stupid, but it really works!"
, "Ordinarily people live and learn. You just live."
, "You only annoy me when you're breathing."
, "Your parents hated you so much your bath toys were an iron and a toaster"
, "You get as much action as a nine button on a microwave."
, "Two wrongs don't make a right, take your parents as an example."
, "You so ugly when who were born the doctor threw you out the window and the window threw you back!"
, "We all sprang from apes, but you didn't spring far enough."
, "I heard you went to a haunted house and they offered you a job."
, "Do you wanna lose ten pounds of ugly fat?\nCut off your head"
, "You stare at frozen juice cans because they say, \"concentrate\"."
,"You're so ugly, when you popped out the doctor said \"Aww what a treasure\" and your mom said \"Yeah, lets bury it.\""
, "You're so ugly, the only dates you get are on a calendar."
, "When was the last time you could see your whole body in the mirror?"
, "You look like a before picture."
, "Am I getting smart with you? How would you know?"
, "You're so dumb, your dog teaches you tricks."
, "Aww, it's so cute when you try to talk about things you don't understand."
, "I may be fat, but you're ugly, and I can lose weight."
, "You're as useless as a screen door on a submarine."
, "You're so ugly, you scared the crap out of the toilet."
, "Your house is so dirty you have to wipe your feet before you go outside."
, "I've seen people like you, but I had to pay admission!"
, "Brains aren't everything. In your case they're nothing."
, "I thought of you all day today. I was at the zoo."
, "I was pro life before I met you."
, "You're so fat, your double chin has a double chin."
, "You must be on the seafood diet. When you see food, you eat it!"
, "Did your parents keep the placenta and throw away the baby?"
, "You must have a very low opinion of people if you think they are your equals."
, "If assholes could fly, this place would be an airport!"
, "100,000 sperm, you were the fastest?"
, "You're so fat a picture of you would fall off the wall!"
, "You're so ugly Hello Kitty said goodbye to you."
, "Just wait till you can't fit your hand in the Pringles tubes, then where will you get your daily nutrition from?"
, "I heard you took an IQ test and they said you're results were negative."
, "You must be the arithmetic man; you add trouble, subtract pleasure, divide attention, and multiply ignorance."
, "If brains were dynamite you wouldn't have enough to blow your nose."
, "Are you always an idiot, or just when I'm around?"
, "So you've changed your mind, does this one work any better?"
, "You're a person of rare intelligence. It's rare when you show any."
, "So, a thought crossed your mind? Must have been a long and lonely journey."
, "It's better to keep your mouth shut and give the 'impression' that you're stupid than to open it and remove all doubt."
, "If what you don't know can't hurt you, you're invulnerable."
, "I'd like to kick you in the teeth, but that would be an improvement!"
, "Even if you were twice as smart, you'd still be stupid!"
, "Don't you need a license to be that ugly?"
, "I fart to make you smell better."
, "You act like your arrogance is a virtue."
, "Ever since I saw you in your family tree, I've wanted to cut it down."
, "You're so stupid, it takes you an hour to cook minute rice."
, "Are your parents siblings?"
, "You're not exactly bad looking. There's just one little problem between your ears - your face!"
, "With a face like yours, I'd wish I was blind."
, "You couldn't pour water out of a boot if the instructions were on the heel."
, "You're so fat, when you wear a yellow rain coat people scream ''taxi''."
, "Everyone who ever loved you was wrong."
, "I'd like to help you out. Which way did you come in?"
, "If ignorance is bliss, you must be the happiest person on earth."
, "Do you ever wonder what life would be like if you'd had enough oxygen at birth?"
, "You're so fat, you have to use a mattress as a maxi-pad."
, "I heard your parents took you to a dog show and you won."
, "You have the perfect face for radio."
, "Your head is so big you have to step into your shirts."
, "You're so ugly, your mother had to tie a steak around your neck to get the dog to play with you!"
, "You must think you're strong, but you only smell strong."
, "Any similarity between you and a human is purely coincidental."
, "Did your parents ever ask you to run away from home?"
, "Looks aren't everything; in your case, they aren't anything"
, "For those who never forget a face, you are an exception."
, "You are so old, your birth-certificate expired."
, "I've come across decomposed bodies that are less offensive than you are."
, "You are so old, even your memory is in black and white."
, "What are you going to do for a face when the baboon wants his butt back?"
, "You're so ugly you make blind kids cry."
, "You're so ugly, you had tinted windows on your incubator."
, "If I want your opinion, I'll give it to you."
, "Come again when you can't stay quite so long."
, "Is that your face? Or did your neck just throw up?"
, "If a crackhead saw you, he'd think he needs to go on a diet."
, "Beauty is skin deep, but ugly is to the bone."
, "You're so stupid you tried to wake a sleeping bag."
, "Your dad's condom is a bigger than your personality."
, "It's too bad stupidity isn't painful."
, "You're so ugly, when you threw a boomerang it didn't come back."
, "If your brain was made of chocolate, it wouldn't fill an M&M."
, "You're so ugly you have to trick or treat over the phone."
, "Keep talking, someday you'll say something intelligent!"
, "Your house is so nasty, I tripped over a rat, and a cockroach stole my wallet."
, "You better hope you marry rich."
, "If my dog had your face, I would shave his butt and make him walk backwards."
, "You're a light eater alright. As soon as it gets light, you starts eating."
, "If you had another brain, it would be lonely."
, "You must have a Teflon brain, because nothing sticks."
, "Nice tan, orange is my favorite color."
, "You conserve toilet paper by using both sides."
, "A sharp tongue is no indication of a keen mind."
, "You are so old, you fart dust."
, "You have a very sympathetic face. It has everyone's sympathy."
, "You have enough fat to make another human."
, "You're so ugly words can't explain it. So I'll just go throw up."
, "I hear the only place you're ever invited is outside."
, "Jesus loves you, everyone else thinks you're an asshole!"
, "You occasionally stumble over the truth, but you quickly pick yourself up and carry on as if nothing happened."
, "Don't get insulted, but is your life devoted to spreading ignorance?"
, "You're the reason they invented double doors!"
, "You are depriving some poor village of its idiot."
, "Just reminding u there is a very fine line between hobby and mental illness."
, "You may not be the best looking girl here, but beauty is only a light switch away!"
, "You are so old, when you were a kid rainbows were black and white."
, "I'm blonde, what's your excuse?"
, "The clothes you wear are so ugly even a scarecrow wouldn't wear them."
, "You'll make a great first wife some day."
, "There are more calories in your stomach than in the local supermarket!"
, "You're so fat, if you got your shoes shined, you'd have to take their word for it!"
, "You're so ugly, they call you the exterminator, because you kill bugs on sight."
, "There's only one problem with your face, I can see it."
, "If your brain exploded, it wouldn't even mess up your hair."
, "People like you are the reason I work out."
, "If I had a dollar for every brain you didn't have, I'd have one dollar."
, "Your hockey team made you goalie so you'd have to wear a mask."
, "You're so fat, when you jump in the air, you get stuck!"
, "If you were any dumber I would have to water you twice a week."
, "I look into your eyes and get the feeling someone else is driving."
, "You couldn't hit water if you fell out of a boat."
, "Your ambition outweighs your relevant skills."
, "You're as useful as an ashtray on a motorcycle."
, "Your ears are so big when you stand on a mountain they look like trophy handles."
, "Your breath is so stinky, we look forward to your farts."
, "Being around you is like having a cancer of the soul."
, "You're so skinny, that you use a bandaid as a maxi-pad."
, "One more wrinkle and you'd pass for a prune."
, "Your asinine simian countenance alludes that your fetid stench has anulled the anthropoid ape species diversity."
, "You have a face only a mother could love - and she hates it!"
, "The sound of your urine hitting the urinal sounds feminine."
, "Two legged stool sample."
, "Is your name Maple Syrup? It should be, you sap."
, "Careful now, don't let your brains go to your head!"
, "You know you're fat when no one has mentioned you're also ginger."
, "Yeah you're pretty, pretty stupid"
, "You're so ugly, if you stuck your head out the window, they'd arrest you for mooning!"
, "You're so old, you walked into an antique shop and they put you on display."
, "You're the reason why women earn 75 cents to the dollar."
, "You're so fat your shadow casts a shadow."
, "I'd say that you're funny but looks aren't everything."
, "Nice shirt, what brand is it? Clearance?"
, "You're so fat, when you take a shower your feet don't get wet!"
, "You're so fat, you have to strap a beeper on your belt to warn people you are backing up."
, "When it comes to IQ, you lose some every time you use the bathroom."
, "The best part of you is still running down your old mans leg."
, "You prefer three left turns to one right turn."
, "It's hard to get the big picture when you have such a small screen."
, "Hold on, I'll go find you a tampon."
, "Your mom must have a really loud bark!"
, "I wish you no harm, but it would have been much better if you had never lived."
, "Your face is so ugly, when you cry the tears run UP your face."
, "Is your name Dan Druff? You get into people's hair."
, "You grow on people, like a wart!"
, "Please tell me you don't home-school your kids."
, "You're so fat your belly button has an echo echo echo..."
, "Your brain must be made out of rocking horse shit."
, "When anorexics see you, they think they need to go on a diet."
, "Did you eat paint chips when you were a kid?"
, "You're stupid because you're blonde."
];

compliments = ["You have very smooth hair."
, "You deserve a promotion."
, "Good effort!"
, "What a fine sweater!"
, "I appreciate all of your opinions."
, "I like your style."
, "Your T-shirt smells fresh."
, "I love what you've done with the place."
, "You are like a spring flower; beautiful and vivacious."
, "I am utterly disarmed by your wit."
, "I really enjoy the way you pronounce the word 'ruby'."
, "You complete me."
, "Well done!"
, "I like your Facebook status."
, "That looks nice on you."
, "I like those shoes more than mine."
, "Nice motor control!"
, "You have a good taste in websites."
, "Your mouse told me that you have very soft hands."
, "You are full of youth."
, "I like your jacket."
, "I like the way you move."
, "You have a good web-surfing stance."
, "You should be a poster child for poster children."
, "Nice manners!"
, "I appreciate you more than Santa appreciates chimney grease."
, "I wish I was your mirror."
, "I find you to be a fountain of inspiration."
, "You have perfect bone structure."
, "I disagree with anyone who disagrees with you."
, "Way to go!"
, "Have you been working out?"
, "With your creative wit, I'm sure you could come up with better compliments than me."
, "I like your socks."
, "You are so charming."
, "Your cooking reminds me of my mother's."
, "You're tremendous!"
, "You deserve a compliment!"
, "Hello, good looking."
, "Your smile is breath taking."
, "How do you get your hair to look that great?"
, "You are quite strapping."
, "I am grateful to be blessed by your presence."
, "Say, aren't you that famous model from TV?"
, "Take a break; you've earned it."
, "Your life is so interesting!"
, "The sound of your voice sends tingles of joy down my back."
, "I enjoy spending time with you."
, "I would share my dessert with you."
, "You can have the last bite."
, "May I have this dance?"
, "I would love to visit you, but I live on the Internet."
, "I love the way you click."
, "You're invited to my birthday party."
, "All of your ideas are brilliant!"
, "If I freeze, it's not a computer virus.  I was just stunned by your beauty."
, "You're spontaneous, and I love it!"
, "You should try out for everything."
, "You make my data circuits skip a beat."
, "You are the gravy to my mashed potatoes."
, "You get an A+!"
, "I'm jealous of the other websites you visit, because I enjoy seeing you so much!"
, "I would enjoy a roadtrip with you."
, "If I had to choose between you or Mr. Rogers, it would be you."
, "I like you more than the smell of Grandma's home-made apple pies."
, "You would look good in glasses OR contacts."
, "Let's do this again sometime."
, "You could go longer without a shower than most people."
, "I feel the need to impress you."
, "I would trust you to pick out a pet fish for me."
, "I'm glad we met."
, "Do that again!"
, "Will you sign my yearbook?"
, "You're so smart!"
, "We should start a band."
, "You're cooler than ice-skating Fonzi."
, "I made this website for you."
, "I heard you make really good French Toast."
, "You're cooler than Pirates and Ninjas combined."
, "Oh, I can keep going."
, "I like your pants."
, "You're pretty groovy, dude."
, "When I grow up, I want to be just like you."
, "I told all my friends about how cool you are."
, "You can play any prank, and get away with it."
, "You have ten of the best fingers I have ever seen!"
, "I can tell that we are gonna be friends."
, "I just want to gobble you up!"
, "You're sweeter than than a bucket of bon-bons!"
, "Treat yourself to another compliment!"
, "You're pretty high on my list of people with whom I would want to be stranded on an island."
, "You're #1 in my book!"
, "Well played."
, "You are well groomed."
, "You could probably lead a rebellion."
, "Is it hot in here or is it just you?"
, "<3"
, "You are more fun than a Japanese steakhouse."
, "Your voice is more soothing than Morgan Freeman's."
, "I like your sleeves. They're real big."
, "You could be drinking whole milk if you wanted to."
, "You're so beautiful, you make me walk into things when I look at you."
, "I support all of your decisions."
, "You are as fun as a hot tub full of chocolate pudding."
, "I usually don't say this on a first date, but will you marry me?"
, "I don't speak much English, but with you all I really need to say is beautiful."
, "Being awesome is hard, but you'll manage."
, "Your skin is radiant."
, "You will still be beautiful when you get older."
, "You could survive a zombie apocalypse."
, "You make me :)"
, "I wish I could move your furniture."
, "I think about you while I'm on the toilet."
, "You're so rad."
, "You're more fun than a barrel of monkeys."
, "You're nicer than a day on the beach."
, "Your glass is the fullest."
, "I find you very relevant."
, "You look so perfect."
, "The only difference between exceptional and amazing is you."
, "Last night I had the hiccups, and the only thing that comforted me to sleep was repeating your name over and over."
, "I like your pearly whites!"
, "Your eyebrows really make your pretty eyes stand out."
, "Shall I compare thee to a summer's day?  Thou art more lovely and more temperate."
, "I love you more than bacon!"
, "You intrigue me."
, "You make me think of beautiful things, like strawberries."
, "I would share my fruit Gushers with you."
, "You're more aesthetically pleasant to look at than that one green color on this website."
, "Even though this goes against everything I know, I think I'm in love with you."
, "You're more fun than bubble wrap."
, "Your smile could illuminate the depths of the ocean."
, "You make babies smile."
, "You make the gloomy days a little less gloomy."
, "You are warmer than a Snuggie."
, "You make me feel like I am on top of the world."
, "Playing video games with you would be fun."
, "Let's never stop hanging out."
, "You're more cuddly than the Downy Bear."
, "I would do your taxes any day."
, "You are a bucket of awesome."
, "You are the star of my daydreams."
, "If you really wanted to, you could probably get a bird to land on your shoulder and hang out with you."
, "My mom always asks me why I can't be more like you."
, "You look great in this or any other light."
, "You listen to the coolest music."
, "You and Chuck Norris are on equal levels."
, "Your body fat percentage is perfectly suited for your height."
, "I am having trouble coming up with a compliment worthy enough for you."
, "If we were playing kickball, I'd pick you first."
, "You're cooler than ice on the rocks."
, "You're the bee's knees."
, "I wish I could choose your handwriting as a font."
, "You definitely know the difference between your and you're."
, "You have good taste."
, "I named all my appliances after you."
, "Your mind is a maze of amazing!"
, "Don't worry about procrastinating on your studies, I know you'll do great!"
, "I like your style!"
, "Hi, I'd like to know why you're so beautiful."
, "If I could count the seconds I think about you, I will die in the process!"
, "If you were in a chemistry class with me, it would be 10x less boring."
, "If you broke your arm, I would carry your books for you."
, "I love the way your eyes crinkle at the corners when you smile."
, "You make me want to be the person I am capable of being."
, "You're a skilled driver."
, "You are the rare catalyst to my volatile compound."
, "You're a tall glass of water!"
, "I'd like to kiss you. Often."
, "You are the wind beneath my wings."
, "Looking at you makes my foot cramps go away instantaneously."
, "I like your face."
, "You are a champ!"
, "You are infatuating."
, "Even my cat likes you."
, "There isn't a thing about you that I don't like."
, "You're so cool, that on a scale of from 1-10, you're elevendyseven."
, "OH, you OWN that ponytail."
, "Your shoes are untied. But for you, it's cool."
, "You have the best laugh ever."
, "We would enjoy a cookout with you!"
, "Your name is fun to say."
, "I love you more than a drunk college student loves tacos."
, "My camera isn't worthy to take your picture."
, "You are the sugar on my rice krispies."
, "Nice belt!"
, "I could hang out with you for a solid year and never get tired of you."
, "You're real happening in a far out way."
, "I bet you could take a punch from Mike Tyson."
, "Your feet are perfect size!"
, "You have very nice teeth."
, "Can you teach me how to be as awesome as you?"
, "Our awkward silences aren't even awkward."
, "Don't worry. You'll do great."
, "I enjoy you more than a good sneeze. A GOOD one."
, "You could invent words and people would use them."
, "You have powerful sweaters."
, "If you were around, I would enjoy doing my taxes."
, "You look like you like to rock."
, "You are better than unicorns and sparkles combined!"
, "You are the watermelon in my fruit salad. Yum!"
, "I dig you."
, "You look better whether the lights are on or off."
, "I am enchanted to meet you."
, "I bet even your farts smell good."
, "I would trust my children with you."
, "You make me forget what I was going to..."
, "Your smile makes me smile."
, "I'd wake up for an 8 a.m. class just so I could sit next to you."
, "You have the moves like Jagger."
, "You're so hot that you denature my proteins."
, "All I want for Christmas is you!"
, "You are the world's greatest hugger."
, "You have a perfectly symmetrical face."
, "If you were in a movie you wouldn't get killed off."
, "Your red ruby lips and wiggly hips make me do flips!"
, "I definitely wouldn't kick you out of bed."
, "They should name an ice cream flavor after you."
, "You're the salsa to my tortilla chips. You spice up my life!"
, "You smell nice."
, "You don't need make-up, make-up needs you."
, "Me without you is like a nerd without braces, a shoe with out laces, asentencewithoutspaces."
, "Just knowing someone as cool as you will read this makes me smile."
, "I would volunteer to take your place in the Hunger Games."
, "If I had a nickel for everytime you did something stupid, I'd be broke!"
, "I'd let you steal the white part of my Oreo."
, "I'd trust you to perform open heart surgery on me... blindfolded!"

]

module.exports = (robot) ->
  robot.respond /insult (.*)/i, (msg) ->
    insult = msg.random insults
    msg.send "hey #{msg.match[1]}, #{insult}"

  robot.respond /compliment (.*)/i, (msg) ->
    compliment = msg.random compliments
    msg.send "hey #{msg.match[1]}, #{compliment}"
